// src/web/partner-portal/src/app/layout/layout.component.ts
import { Component } from '@angular/core'
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router'
import { AuthService } from '../services/auth.service'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, CommonModule],
  template: `
    <div class="layout">
      <aside class="sidebar">
        <div class="logo">ShopOS Partner</div>
        <nav>
          <a *ngFor="let l of links" [routerLink]="l.to" routerLinkActive="active" [routerLinkActiveOptions]="{exact: l.to === '/'}" class="nav-link">{{ l.label }}</a>
        </nav>
        <button class="logout" (click)="auth.logout()">Logout</button>
      </aside>
      <div class="content-wrap">
        <header class="topbar"><span class="email">{{ auth.email() }}</span></header>
        <main class="main"><router-outlet /></main>
      </div>
    </div>`,
  styles: [`
    .layout { display: flex; height: 100vh; font-family: system-ui, sans-serif; }
    .sidebar { width: 220px; background: #111; color: #fff; display: flex; flex-direction: column; }
    .logo { padding: 1.5rem; font-weight: 700; font-size: 1.1rem; border-bottom: 1px solid #374151; }
    .nav-link { display: block; padding: 0.625rem 1.5rem; color: #9ca3af; text-decoration: none; font-size: 0.875rem; }
    .nav-link.active { color: #fff; background: #374151; }
    .logout { margin-top: auto; padding: 1rem 1.5rem; background: none; border: none; color: #9ca3af; cursor: pointer; text-align: left; font-size: 0.875rem; }
    .content-wrap { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
    .topbar { height: 60px; background: #fff; border-bottom: 1px solid #e5e7eb; display: flex; align-items: center; padding: 0 1.5rem; }
    .email { margin-left: auto; color: #6b7280; font-size: 0.875rem; }
    .main { flex: 1; overflow: auto; padding: 1.5rem; background: #f9fafb; }
  `]
})
export class LayoutComponent {
  constructor(public auth: AuthService) {}
  links = [
    { to: '/',           label: 'Dashboard'  },
    { to: '/contracts',  label: 'Contracts'  },
    { to: '/orders',     label: 'Orders'     },
    { to: '/invoices',   label: 'Invoices'   },
    { to: '/quotes',     label: 'Quotes'     },
    { to: '/profile',    label: 'Profile'    },
  ]
}

// src/web/developer-portal-ui/src/components/Layout.tsx
import { Outlet, NavLink } from 'react-router-dom'
import { useAuth } from '../store/auth'

const links = [
  { to: '/',          label: 'Dashboard'  },
  { to: '/api-keys',  label: 'API Keys'   },
  { to: '/webhooks',  label: 'Webhooks'   },
  { to: '/sandbox',   label: 'Sandbox'    },
  { to: '/analytics', label: 'Analytics'  },
  { to: '/docs',      label: 'Docs'       },
]

export default function Layout() {
  const { email, logout } = useAuth()
  return (
    <div style={{display:'flex',height:'100vh',fontFamily:'system-ui,sans-serif'}}>
      <aside style={{width:220,background:'#111',color:'#fff',display:'flex',flexDirection:'column',flexShrink:0}}>
        <div style={{padding:'1.5rem',fontWeight:700,fontSize:'1.1rem',borderBottom:'1px solid #374151'}}>Developer Portal</div>
        <nav style={{padding:'0.5rem 0',flex:1}}>
          {links.map(l => (
            <NavLink key={l.to} to={l.to} end={l.to === '/'}
              style={({ isActive }) => ({ display:'block',padding:'0.625rem 1.5rem',color:isActive?'#fff':'#9ca3af',background:isActive?'#374151':'transparent',textDecoration:'none',fontSize:'0.875rem' })}>
              {l.label}
            </NavLink>
          ))}
        </nav>
        <div style={{padding:'1rem 1.5rem',borderTop:'1px solid #374151'}}>
          <p style={{fontSize:'0.75rem',color:'#9ca3af',marginBottom:'0.5rem',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{email}</p>
          <button onClick={logout} style={{fontSize:'0.75rem',color:'#9ca3af',background:'none',border:'none',cursor:'pointer',padding:0}}>Logout</button>
        </div>
      </aside>
      <div style={{flex:1,display:'flex',flexDirection:'column',overflow:'hidden'}}>
        <header style={{height:60,background:'#fff',borderBottom:'1px solid #e5e7eb',display:'flex',alignItems:'center',padding:'0 1.5rem',flexShrink:0}}>
          <span style={{fontWeight:600,fontSize:'0.875rem',color:'#374151'}}>ShopOS Developer Platform</span>
        </header>
        <main style={{flex:1,overflow:'auto',padding:'1.5rem',background:'#f9fafb'}}><Outlet /></main>
      </div>
    </div>
  )
}
