// src/web/seller-portal/src/views/Orders.vue
<template>
  <div>
    <h1 class="title">Orders</h1>
    <div class="table-wrap">
      <p v-if="loading" class="empty">Loading...</p>
      <table v-else-if="orders.length">
        <thead><tr><th>Order ID</th><th>Buyer</th><th>Items</th><th>Total</th><th>Status</th><th>Date</th></tr></thead>
        <tbody>
          <tr v-for="o in orders" :key="o.id">
            <td>#{{ o.id.slice(0,8).toUpperCase() }}</td><td>{{ o.buyerEmail }}</td><td>{{ o.items }}</td>
            <td>${{ o.total.toFixed(2) }}</td><td>{{ o.status }}</td>
            <td>{{ new Date(o.createdAt).toLocaleDateString() }}</td>
          </tr>
        </tbody>
      </table>
      <p v-else class="empty">No orders yet.</p>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { api } from '../api/client'
import type { Order } from '../types'
const orders = ref<Order[]>([]); const loading = ref(true)
onMounted(() => api.get<Order[]>('/seller/orders').then(d => orders.value = d).catch(() => {}).finally(() => loading.value = false))
</script>
<style scoped>
.title { font-size: 1.5rem; font-weight: 700; margin-bottom: 1.5rem; }
.table-wrap { background: #fff; border: 1px solid #e5e7eb; border-radius: 0.5rem; overflow: hidden; }
table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
th { text-align: left; padding: 0.75rem 1rem; font-weight: 600; border-bottom: 2px solid #e5e7eb; }
td { padding: 0.75rem 1rem; border-bottom: 1px solid #f3f4f6; }
.empty { text-align: center; padding: 2rem; color: #9ca3af; }
</style>

// src/web/mobile-app/app/(tabs)/orders.tsx
import { useEffect, useState } from 'react'
import { View, Text, FlatList, StyleSheet, ActivityIndicator } from 'react-native'
import { api } from '../../src/api/client'

interface Order { id: string; status: string; total: number; createdAt: string; items: number }

export default function OrdersScreen() {
  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => { api.get<Order[]>('/orders/me').then(setOrders).catch(()=>{}).finally(()=>setLoading(false)) }, [])

  if (loading) return <View style={s.center}><ActivityIndicator size="large" /></View>

  return (
    <View style={s.container}>
      <Text style={s.title}>My Orders</Text>
      {orders.length === 0 ? <Text style={s.empty}>No orders yet.</Text> : (
        <FlatList data={orders} keyExtractor={o => o.id} renderItem={({ item: o }) => (
          <View style={s.card}>
            <View style={s.row}>
              <Text style={s.id}>#{o.id.slice(0,8).toUpperCase()}</Text>
              <Text style={[s.status, { color: o.status === 'delivered' ? '#059669' : '#374151' }]}>{o.status}</Text>
            </View>
            <Text style={s.meta}>{o.items} item(s) · ${o.total.toFixed(2)}</Text>
            <Text style={s.date}>{new Date(o.createdAt).toLocaleDateString()}</Text>
          </View>
        )} />
      )}
    </View>
  )
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff', padding: 16 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 22, fontWeight: '700', marginBottom: 16 },
  card: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8, padding: 14, marginBottom: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  id: { fontWeight: '700', fontSize: 15 },
  status: { fontWeight: '600', fontSize: 13 },
  meta: { color: '#6b7280', fontSize: 13, marginBottom: 2 },
  date: { color: '#9ca3af', fontSize: 12 },
  empty: { textAlign: 'center', marginTop: 40, color: '#9ca3af' },
})
