// src/web/admin-dashboard/src/pages/Analytics.tsx
export default function Analytics() {
  return (
    <div>
      <h1 style={{fontSize:'1.5rem',fontWeight:700,marginBottom:'1.5rem'}}>Analytics</h1>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1rem'}}>
        {['Revenue Over Time','Orders by Status','Top Products','User Growth'].map(title => (
          <div key={title} style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:'0.5rem',padding:'1.5rem',minHeight:240}}>
            <h2 style={{fontWeight:600,marginBottom:'1rem',fontSize:'0.875rem',color:'#374151'}}>{title}</h2>
            <div style={{height:160,background:'#f9fafb',borderRadius:'0.25rem',display:'flex',alignItems:'center',justifyContent:'center',color:'#9ca3af',fontSize:'0.875rem'}}>
              Chart — connect to analytics-service
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// src/web/seller-portal/src/views/Analytics.vue
<template>
  <div>
    <h1 class="title">Analytics</h1>
    <div class="grid">
      <div v-for="t in titles" :key="t" class="chart-card">
        <h2>{{ t }}</h2>
        <div class="chart-placeholder">Connect to analytics-service</div>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
const titles = ['Revenue Over Time', 'Top Listings', 'Orders by Day', 'Conversion Rate']
</script>
<style scoped>
.title { font-size: 1.5rem; font-weight: 700; margin-bottom: 1.5rem; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
.chart-card { background: #fff; border: 1px solid #e5e7eb; border-radius: 0.5rem; padding: 1.5rem; }
.chart-card h2 { font-size: 0.875rem; font-weight: 600; color: #374151; margin-bottom: 1rem; }
.chart-placeholder { height: 160px; background: #f9fafb; border-radius: 0.25rem; display: flex; align-items: center; justify-content: center; color: #9ca3af; font-size: 0.875rem; }
</style>
