// src/web/admin-dashboard/src/pages/Dashboard.tsx
import { useEffect, useState } from 'react'
import StatCard from '../components/StatCard'
import { statsApi } from '../api/client'
import type { DashboardStats } from '../types'

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStats | null>(null)
  useEffect(() => { statsApi.get().then(setStats).catch(() => {}) }, [])

  return (
    <div>
      <h1 style={{fontSize:'1.5rem',fontWeight:700,marginBottom:'1.5rem'}}>Dashboard</h1>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(220px,1fr))',gap:'1rem',marginBottom:'2rem'}}>
        <StatCard label="Total Revenue"   value={stats?.totalRevenue ?? 0}   change={stats?.revenueChange} prefix="$" />
        <StatCard label="Total Orders"    value={stats?.totalOrders ?? 0}    change={stats?.ordersChange} />
        <StatCard label="Total Users"     value={stats?.totalUsers ?? 0}     change={stats?.usersChange} />
        <StatCard label="Total Products"  value={stats?.totalProducts ?? 0} />
      </div>
      <div style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:'0.5rem',padding:'1.5rem'}}>
        <h2 style={{fontWeight:600,marginBottom:'1rem'}}>Quick Actions</h2>
        <div style={{display:'flex',gap:'0.75rem',flexWrap:'wrap'}}>
          <a href="/orders"   style={{padding:'0.5rem 1rem',background:'#f3f4f6',borderRadius:'0.375rem',fontSize:'0.875rem'}}>View Orders</a>
          <a href="/products" style={{padding:'0.5rem 1rem',background:'#f3f4f6',borderRadius:'0.375rem',fontSize:'0.875rem'}}>Manage Products</a>
          <a href="/users"    style={{padding:'0.5rem 1rem',background:'#f3f4f6',borderRadius:'0.375rem',fontSize:'0.875rem'}}>View Users</a>
        </div>
      </div>
    </div>
  )
}

// src/web/seller-portal/src/views/Dashboard.vue
<template>
  <div>
    <h1 class="title">Dashboard</h1>
    <div class="stats-grid">
      <StatCard label="Total Revenue"   :value="stats?.totalRevenue ?? 0"   prefix="$" />
      <StatCard label="Total Sales"     :value="stats?.totalSales ?? 0" />
      <StatCard label="Pending Orders"  :value="stats?.pendingOrders ?? 0" />
      <StatCard label="Active Listings" :value="stats?.activeListings ?? 0" />
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import StatCard from '../components/StatCard.vue'
import { api } from '../api/client'
import type { Stats } from '../types'
const stats = ref<Stats | null>(null)
onMounted(() => api.get<Stats>('/seller/stats').then(d => stats.value = d).catch(() => {}))
</script>
<style scoped>
.title { font-size: 1.5rem; font-weight: 700; margin-bottom: 1.5rem; }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem; }
</style>
